### ISSUE TITLE
Ajuster la fonctionnalité de retraitement d'une modération via bouton « Retraiter »

### ISSUE THREAD

**Issue by laetitiasanogo** [numerique-gouv/hyyypertool#329]
Lorsque l’on retraite une modération, et que l’on refuse la demande, l’utilisateur doit être retiré automatiquement de l’organisation correspondante à la modération

**Comment by douglasduteil** [comment]
- [ ] ensure that the refused users are not un the organization by always trying to removing the user from the organization
